module.exports={
    HomeNav:[
        {key:'home',
        name: 'Home',
        icon: 'mdi-home',
        to: 'home'},
        {key:'about',
        name: 'About',
        icon:'mdi-information-outline',
        to: 'about'},
        {key:'connect',
        name: 'Connect',
        icon: 'mdi-human-greeting-proximity',
        submenu:[
            {key: 'cellGroups',
            name: 'Cell Groups',
            icon: 'mdi-account-group-outline',
            to: 'cellGroups'},
            {key: 'childrenMinistry',
            name: `Childen's Ministry`,
            icon: 'mdi-lightbulb-group'},
            {key: 'youthMinistry',
            name: `Youth Ministry`,
            icon: 'mdi-lightbulb-group'},
            {key: 'musicMinistry',
            name: `Music Ministry`,
            icon: 'mdi-guitar-pick-outline',
            to: 'musicMinistry'},
            {key: 'danceMinistry',
            name: `Dance Ministry`,
            icon: 'mdi-human-female-dance'},
            {key: 'jteamMinistry',
            name: `JTeam (Hakot) Ministry`,
            icon: 'mdi-bag-carry-on-check'},
            {key: 'usheringMinistry',
            name: `Ushering Ministry`,
            icon: 'mdi-human-queue'},
        ]},
        {key:'resources',
        name: 'Resources',
        icon: 'mdi-book-cross',
        submenu:[
            {key:'knowJesus',
            name: 'Know Jesus',
            icon:'mdi-book-cross'},
            {key:'events',
            name: 'Events',
            icon:'mdi-calendar-check-outline'},
            {key:'sermons',
            name: 'Sermons',
            icon:'mdi-page-next-outline'},
            {key:'blogs',
            name: 'Blogs',
            icon:'mdi-blogger'}
        ]},
        {key:'give',
        name: 'Give',
        icon: 'mdi-hand-heart'},
        {key:'contact',
        name: 'Contact',
        icon: 'mdi-face-agent'}

    ]
}